# Generated by Django 5.1.3 on 2024-12-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('person_type', models.CharField(choices=[('Driver', 'Driver'), ('Rider', 'Rider')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('car_license', models.CharField(max_length=50)),
                ('seats_available', models.PositiveIntegerField()),
                ('route', models.JSONField(default=list)),
                ('timing', models.CharField(default='', max_length=20)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to='backend.person')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('feedback', models.TextField(max_length=500)),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_ratings', to='backend.person')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ratings', to='backend.person')),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to='backend.person')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='backend.driver')),
                ('riders', models.ManyToManyField(related_name='bookings', to='backend.rider')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locations', models.JSONField()),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_route', to='backend.driver')),
            ],
        ),
    ]
